### ISSUE TITLE
build 0.6.19.1. state stuck in taking snapshot

### ISSUE THREAD

**Issue by chris-chensy** [twrecked/hass-aarlo#262] opened 2020-05-23 13:27 UTC
I have updated it to the build .19.1. It seems requesting a snapshot during recording is still problematic. The snapshot wasn't taken after the recording finished. Now the camera state is stuck in taking snapshot forever (no snapshot updated). My device is arlo ultra.

_Originally posted by @chris-chensy in https://github.com/twrecked/hass-aarlo/issues/250#issuecomment-633053163_

**Comment by twrecked** [comment] 2020-05-23 13:48
I'm not fixing this in the 0.6 releases. It will be fixed in 0.7. 

I'll be pushing a 0.7.alpha.3 later today. Give it a try, the whole code around snapshots has changed.

**Comment by twrecked** [comment] 2020-07-27 13:33
Duplicate of #271 

Marking it as a duplicate of this one because it has more informatiom.

**Closed by twrecked** 2020-07-27 13:33 UTC
Labels: wontfix
