### ISSUE TITLE
why now need code?

### ISSUE THREAD

**Issue by unecc** [twrecked/hass-aarlo#965] opened 2024-06-13 21:13 UTC
Hi, since some day, arlo on hass can't be activated or disactivated

error is "Invocazione del servizio alarm_control_panel/alarm_arm_home non riuscita. Validation error: Arming requires a code but none was given for alarm_control_panel.aarlo_nodo_cas"

if i activate code (PIN in arlo dash) works..

if i remove PIN (as before) and add "no code needed" not works always some error

"Invocazione del servizio alarm_control_panel/alarm_arm_home non riuscita. Validation error: Arming requires a code but none was given for alarm_control_panel.aarlo_nodo_cas"

What's wrong?

**Comment by twrecked** [comment] 2024-06-13 21:24
It's an upgrade issue and this report is a duplicate of #962 #963 #964

**Closed by twrecked** 2024-06-13 21:24 UTC
