### ISSUE TITLE
start recording service failed

### ISSUE THREAD

**Issue by johro897** [twrecked/hass-aarlo#311] opened 2020-09-13 19:26 UTC
I am trying to start a recording and get the below errors.

2020-09-13 21:22:26 INFO (MainThread) [custom_components.aarlo.camera] camera_start_recording service called
2020-09-13 21:22:26 INFO (MainThread) [custom_components.aarlo.camera] camera.aarlo_2 start recording(duration=30)
2020-09-13 21:22:26 DEBUG (SyncWorker_48) [pyaarlo] _start_stream2::activities={'recording-stream'}
2020-09-13 21:22:26 DEBUG (SyncWorker_48) [pyaarlo] post+response running
2020-09-13 21:22:26 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5***to 5***
2020-09-13 21:22:26 DEBUG (ArloEventStream) [pyaarlo] 2 CAMERA got one cameras/5***
2020-09-13 21:22:26 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5***/activityState=startUserStream
2020-09-13 21:22:26 DEBUG (ArloEventStream) [custom_components.aarlo.camera] callback:2:activityState:startUserStream
2020-09-13 21:22:26 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5***to 5***
2020-09-13 21:22:26 DEBUG (ArloEventStream) [pyaarlo] 2 CAMERA got one cameras/5***
2020-09-13 21:22:26 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5***/activityState=startUserStream
2020-09-13 21:22:26 DEBUG (ArloEventStream) [custom_components.aarlo.camera] callback:2:activityState:startUserStream
2020-09-13 21:22:29 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5***to 5***
2020-09-13 21:22:29 DEBUG (ArloEventStream) [pyaarlo] 2 CAMERA got one cameras/5***
2020-09-13 21:22:29 DEBUG (ArloEventStream) [pyaarlo] _event::stream::activities={'recording-stream', 'user-stream-active'}
2020-09-13 21:22:29 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5***/activityState=userStreamActive
2020-09-13 21:22:29 DEBUG (ArloEventStream) [custom_components.aarlo.camera] callback:2:activityState:userStreamActive
2020-09-13 21:22:29 DEBUG (SyncWorker_48) [pyaarlo] url=*********
2020-09-13 21:22:29 INFO (SyncWorker_48) [custom_components.aarlo.camera] 2 attaching hidden stream for duration 15
2020-09-13 21:22:29 WARNING (MainThread) [custom_components.aarlo.camera] camera.aarlo_2 start recording service failed

**Comment by twrecked** [comment] 2020-09-15 13:15
What was at the start of the url? Was it rtsp or https?

**Comment by halytech** [comment] 2020-09-16 00:49
I have this same issue.  Same URL seems to work fine for streaming to the Lovelace card.  Here's the URL it uses: (IDs redacted):

`2020-09-15 19:20:00 DEBUG (MainThread) [custom_components.aarlo.switch] get state Big Brother Siren form
2020-09-15 19:20:00 DEBUG (MainThread) [custom_components.aarlo.switch] get state for All Sirens
2020-09-15 19:20:01 DEBUG (SyncWorker_0) [pyaarlo] url=rtsps://arlostreaming(url_junk)-z2-prod.wowza.arlo.com:443/vzmodulelive/(device_stuff_here)?egressToken=(weird_long_token_here)&userAgent=iOS&cameraId=(some_unique_camera_id_here_that_sort_of_matches_the_device_stuff_before)
2020-09-15 19:20:01 INFO (SyncWorker_0) [custom_components.aarlo.camera] front_door attaching hidden stream for duration 15
2020-09-15 19:20:01 WARNING (MainThread) [custom_components.aarlo.camera] camera.aarlo_front_door start recording service failed
`

**Comment by twrecked** [comment] 2020-09-17 14:42
It's working for me. Can you send me the record command you used?

**Comment by johro897** [comment] 2020-09-17 15:13
Was using the aarlo.camera_start_recording in Developer tools->Services
with service data:
entity_id: camera.aarlo_2
duration: 30

**Comment by johro897** [comment] 2020-09-17 15:14
> What was at the start of the url? Was it rtsp or https?

url=rtsps://arlostreaming1188-z1-prod.wowza.arlo.com:443/

**Comment by Kras-s-savchiK** [comment] 2020-09-17 20:18
If I understand correctly, - I can use RTSP stream from Arlo?
If yes - how can I find this url?
Thx!

**Comment by twrecked** [comment] 2020-09-19 11:48
@Kras-s-savchiK 
Getting to the Arlo streams is complicated. Unlike other cameras the stream isn't always on so you just can't use `rtsps://ipaddress/stream`, you need to ask Arlo to start the stream and it will return the URL.

Aarlo provides a websocket you can get use to start the stream `aarlo_stream_url`. Check the Lovelace Aarlo card on how to call the websocket or look [here](https://developers.home-assistant.io/docs/api/websocket/).

**Comment by ecostin** [comment] 2020-10-05 06:27
+1 start recording service failed whenever recording is attempted. Recording works from Aarlo's web interface.

**Comment by hanskroner** [comment] 2020-10-08 13:59
Starting a recording fails for me as well, albeit somewhat differently. I'm using the _aarlo.camera_request_video_to_file_ service call to record locally instead of to the cloud.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 137, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1315, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1350, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/aarlo/camera.py", line 200, in async_service_callback
    await hass.async_add_executor_job(service_callback, call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aarlo/camera.py", line 191, in service_callback
    camera_video_to_file_service(hass, call)
  File "/config/custom_components/aarlo/camera.py", line 964, in camera_video_to_file_service
    out_file.write(video)
TypeError: a bytes-like object is required, not 'NoneType'
```

**Comment by twrecked** [comment] 2020-10-08 14:46
I've just noticed I have a race condition in the state machine. I'm looking at it.

**Comment by twrecked** [comment] 2020-11-11 18:18
Are people still seeing this with the latest release? I tidied the state machine to help with snapshots and recording.

**Comment by joch** [comment] 2020-11-12 07:56
Getting this when using `aarlo.camera_start_recording`:


```
2020-11-12 08:52:04 INFO (SyncWorker_24) [custom_components.aarlo.camera] camera_start_recording service called
2020-11-12 08:52:04 INFO (SyncWorker_24) [custom_components.aarlo.camera] camera.aarlo_living_room start recording(duration=10)
2020-11-12 08:52:04 DEBUG (SyncWorker_24) [pyaarlo] _start_stream2::reqs='set()',local='{'recording'}',remote='set()'
2020-11-12 08:52:05 DEBUG (SyncWorker_24) [pyaarlo] url=rtsps://arlostreaming32-z1-prod.wowza.arlo.com:443/vzmodulelive/4XH27XXXXXXXX_160516XXXXXX?egressToken=65b09ee5_76c1_407e_XXXXXXXX&userAgent=iOS&cameraId=4XH2737WA5A36_XXXXXXXX
2020-11-12 08:52:05 INFO (SyncWorker_24) [custom_components.aarlo.camera] living_room attaching hidden stream for duration 20
2020-11-12 08:52:05 WARNING (SyncWorker_24) [custom_components.aarlo.camera] camera.aarlo_living_room start recording service failed
2020-11-12 08:52:05 DEBUG (ArloEventStream) [pyaarlo] sending cameras/4XH273XXXXX to 4XH273XXXXXX
2020-11-12 08:52:05 DEBUG (ArloEventStream) [pyaarlo] Living Room CAMERA got one cameras/4XH273XXXXXX
2020-11-12 08:52:05 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/4XH273XXXXX/activityState=startUserStream
2020-11-12 08:52:05 DEBUG (ArloEventStream) [custom_components.aarlo.camera] callback:Living Room:activityState:startUserStream
2020-11-12 08:52:05 DEBUG (ArloEventStream) [custom_components.aarlo.switch] callback:Living Room Snapshot:activityState:startUserStream
2020-11-12 08:52:05 DEBUG (ArloEventStream) [pyaarlo] sending cameras/4XH2737XXXXX to 4XH273XXXX
2020-11-12 08:52:05 DEBUG (ArloEventStream) [pyaarlo] Living Room CAMERA got one cameras/4XH273XXXXX
2020-11-12 08:52:05 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/4XH273XXXXXXactivityState=startUserStream
2020-11-12 08:52:05 DEBUG (ArloEventStream) [custom_components.aarlo.camera] callback:Living Room:activityState:startUserStream
2020-11-12 08:52:05 DEBUG (ArloEventStream) [custom_components.aarlo.switch] callback:Living Room Snapshot:activityState:startUserStream
```

**Comment by johro897** [comment] 2020-11-16 07:10
Yes, still seeing 
WARNING (SyncWorker_44) [custom_components.aarlo.camera] camera.aarlo_driveway start recording service failed

**Comment by hennarah** [comment] 2020-11-22 05:58
> Yes, still seeing
> WARNING (SyncWorker_44) [custom_components.aarlo.camera] camera.aarlo_driveway start recording service failed

Same here, getting the exact error

**Comment by Snowguy82** [comment] 2020-12-07 00:20
> 
> 
> Are people still seeing this with the latest release? I tidied the state machine to help with snapshots and recording.

Yes I am still getting this error.

**Comment by twrecked** [comment] 2020-12-08 03:30
I might know what this is. Can you add the following to your config:

```yaml
homeassistant:
  ...
  whitelist_external_dirs:
    - /tmp
```

When we record a stream if we don't read from the stream Arlo can close it prematurely. We attach a stream but we have to write it somewhere, the code stores it in `/tmp` which you need to have whitelisted.

**Comment by joch** [comment] 2020-12-08 12:33
Just confirmed that the whitelisting did not help, but just saw that you found another issue with mpeg-dash.

**Comment by twrecked** [comment] 2020-12-08 14:20
Can you try 0.7.0.3? It won't fix the issue but it should display the real reason the record failed.

**Comment by joch** [comment] 2020-12-08 14:37
Upgraded, and got this:

```
2020-12-08 15:26:46 WARNING (SyncWorker_33) [custom_components.aarlo.camera] camera.aarlo_hallway start recording service failed - Can't write /tmp/aarlo-hidden-hallway.mp4, no access to path!
```

So you were right! I was adding the `whitelist_external_dirs` in a package, which apparently doesn't work. After moving it to the main config (and renaming to `allowlist_external_dirs` which seems to be the new name), it started working.

**Comment by twrecked** [comment] 2020-12-08 14:46
I should have added the error in the first place!

There still might be an issue with stream types - I've set up my `user_agent` as `linux` so I can't record for more than 30 seconds - so I'll take a look at that.

**Comment by twrecked** [comment] 2020-12-15 13:54
Closing, it was an `allowlist` issue.

**Closed by twrecked** 2020-12-15 13:54 UTC
