### ISSUE TITLE
SSL Error on Startup

### ISSUE THREAD

**Issue by dw1562** [twrecked/hass-aarlo#742] opened 2023-05-09 22:24 UTC
I restarted my HA this morning and I got the following error from hass-aarlo.    It has been working fine for some time now and nothing has changed with my setup.   I'm no expert but from the error message it seems like this may be an issue on the Arlo side of things???

aarlo Component Setup
**Error: general-error=SSLCertVerificationError**
Traceback (most recent call last):
File "/config/custom_components/aarlo/pyaarlo/backend.py", line 485, in _mqtt_main
self._event_client.connect(MQTT_HOST, port=443, keepalive=60)
File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1073, in reconnect
sock.do_handshake()
File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
self._sslobj.do_handshake()
**ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mqtt-cluster.arloxcld.com'. (_ssl.c:1007)**

If error persists you might need to change config and restart.

**Comment by dw1562** [comment] 2023-05-09 22:43
Sorry I did look at the other post but I didn't see any with SSL in the heading.   I just looked a little further and see that the issue below my post is for this exact issue.   Trying the workaround now.

**Comment by twrecked** [comment] 2023-05-09 23:38
Duplicate of #741

**Closed by twrecked** 2023-05-09 23:38 UTC
