### ISSUE TITLE
SSL certificate error

### ISSUE THREAD

**Issue by yank555-lu** [twrecked/hass-aarlo#748] opened 2023-05-11 20:45 UTC
This started a couple of daya ago pn a working config (using 2fa on a gmail account) ... I keep seeing 2fa otp emails arriving fine.

Checking the SSL for mqtt-cluster.arloxcld.com gives indeed that same error. The CN in the certificate says mqtt-cluster-z1.arloxcld.com

Log Details (ERROR)
This error originated from a custom integration.
Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:712
Integration: aarlo ([documentation](https://github.com/twrecked/hass-aarlo/blob/master/README.md), [issues](https://github.com/twrecked/hass-aarlo/issues))
First occurred: 22:25:56 (201 occurrences)
Last logged: 22:32:10

general-error=SSLCertVerificationError Traceback (most recent call last): File "/config/custom_components/aarlo/pyaarlo/backend.py", line 485, in _mqtt_main self._event_client.connect(MQTT_HOST, port=443, keepalive=60) File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect return self.reconnect() File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1073, in reconnect sock.do_handshake() File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake self._sslobj.do_handshake() ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mqtt-cluster.arloxcld.com'. (_ssl.c:1007)

**Comment by yank555-lu** [comment] 2023-05-11 20:52
I tried changing pyaarlo/constant.py MQTT_HOST to mqtt-cluster-z1.arloxcld.com

This gave me :

aarlo Component Setup
Error: general-error=WebsocketConnectionError
Traceback (most recent call last):
File "/config/custom_components/aarlo/pyaarlo/backend.py", line 485, in _mqtt_main
self._event_client.connect(MQTT_HOST, port=443, keepalive=60)
File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1080, in reconnect
sock = WebsocketWrapper(sock, self._host, self._port, self._ssl,
File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3713, in init
self._do_handshake(extra_headers)
File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3797, in _do_handshake
raise WebsocketConnectionError("WebSocket handshake error")
paho.mqtt.client.WebsocketConnectionError: WebSocket handshake error

If error persists you might need to change config and restart.

**Comment by twrecked** [comment] 2023-05-11 20:56
Duplicate of #741

**Closed by twrecked** 2023-05-11 20:56 UTC
