### ISSUE TITLE
SUPPORT_ALARM_ARM_AWAY error

### ISSUE THREAD

**Issue by PrimitixLuke** [twrecked/hass-aarlo#883] opened 2024-02-07 21:22 UTC
Logger: homeassistant.components.alarm_control_panel.const
Source: helpers/deprecation.py:205
Integration: Pannello di controllo degli allarmi (documentation, issues)
First occurred: 22:15:28 (4 occurrences)
Last logged: 22:15:28

SUPPORT_ALARM_ARM_AWAY was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_AWAY instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues
SUPPORT_ALARM_ARM_HOME was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_HOME instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues
SUPPORT_ALARM_ARM_NIGHT was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_NIGHT instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues
SUPPORT_ALARM_TRIGGER was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.TRIGGER instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues

**Comment by twrecked** [comment] 2024-02-07 21:33
Duplicate of #872

**Closed by twrecked** 2024-02-07 21:33 UTC
