### ISSUE TITLE
aarlo Component Setup Error: authentication failed

### ISSUE THREAD

**Issue by unterleib** [twrecked/hass-aarlo#452] opened 2021-06-03 18:09 UTC
HI since yesterday I have to following issue. I have not changed anything to the config yet!

Upgraded this morning to aarlo v0.7.1

No changes! Still the same issue!

This error originated from a custom integration.

Logger: custom_components.aarlo
Source: custom_components/aarlo/__init__.py:444 
Integration: Arlo Camera Support (documentation, issues) 
First occurred: 1:54:32 PM (2 occurrences) 
Last logged: 1:54:51 PM

unable to connect to Arlo: attempt=1,sleep=15,error=authentication failed
unable to connect to Arlo: attempt=2,sleep=30,error=authentication failed

**Comment by borski** [comment] 2021-06-03 19:34
I have this issue too.

**Comment by twrecked** [comment] 2021-06-03 19:43
This is a duplicate of 451. I'm also seeing the issue, it might be a `cloudscraper` problem but I'm trying some header tidy as well.

**Closed** 2021-06-03 19:44 UTC
