### ISSUE TITLE
Include component in HACS

### ISSUE THREAD

**Issue by pichlerralf** [twrecked/hass-aarlo#82] opened 2019-07-03 12:01 UTC
Lots of people are currently changing from custum_updater to the new HACS, which is much more user friendly.

So i am opening an issue here because surely not only me would love to see your component is included into HACS (Home Assistant Community Store):
https://github.com/custom-components/hacs

Thanks very much in advance!

P.S.: thanks very much for providing such a great component for HA!

Regards,
Ralf Pichler

**Comment by cbfreeborn** [comment] 2019-07-05 20:49
I would definitely second that request.

**Comment by twrecked** [comment] 2019-07-05 21:03
I'm planning on doing I'm just away from my computer for the next week.

**Comment by ryanwinter** [comment] 2019-07-09 18:21
HACS would be nice, although replacing the existing arlo component would be the best end result.

**Comment by twrecked** [comment] 2019-07-13 12:07
Duplicate of #79

**Closed** 2019-07-13 12:07 UTC
