### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch

### ISSUE THREAD

**Issue by barto64** [twrecked/hass-aarlo#749] opened 2023-05-12 14:48 UTC
Hey,

Getting the below error in HA log related to Arlo Cameras. They do not obviously work.

2023-05-12 14:24:09.777 ERROR (ArloEventStream) [pyaarlo] general-error=SSLCertVerificationError
Traceback (most recent call last):
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 490, in _mqtt_main
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mqtt-cluster.arloxcld.com'. (_ssl.c:1007)

**Comment by twrecked** [comment] 2023-05-12 15:13
Duplicate of #741 
(which I just renamed to better show the issue)

See release notes from latest version.

**Closed by twrecked** 2023-05-12 15:13 UTC

**Comment by barto64** [comment] 2023-05-12 15:18
My fault, sorry !!!

**Comment by twrecked** [comment] 2023-05-12 15:39
No worries. You're not the first person to duplicate the issue. It took me too long to realise the original bug title was burying the lede.

Hope it's working now.
