### ISSUE TITLE
TEMP_CELSIUS error

### ISSUE THREAD

**Issue by PrimitixLuke** [twrecked/hass-aarlo#881] opened 2024-02-07 21:21 UTC
Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 22:15:20 (1 occurrences)
Last logged: 22:15:20

TEMP_CELSIUS was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues

**Comment by twrecked** [comment] 2024-02-07 21:34
Duplicate of #872

**Closed by twrecked** 2024-02-07 21:34 UTC
