### ISSUE TITLE
New HA infrastructure requires services.yaml?

### ISSUE THREAD

**Issue by Swiftnesses** [twrecked/hass-aarlo#50] opened 2019-04-30 15:02 UTC
Hi Steve,

It seems plugins now require a simple services.yaml, example (taken from another plugin!):

```
# Example services.yaml entry

#  SPDX-License-Identifier: Apache-2.0
update_last_called:
  # Description of the service
  description: Forces update of last_called echo device for each Alexa account.
  # Different fields that your service accepts
  fields:
    # Key of the field
    email:
      # Description of the field
      description: List of Alexa accounts to update. If empty, will update all known accounts
      # Example value that can be passed for this field
      example: 'my_email@alexa.com'
```

Do we need this for the Aarlo services?

**Comment by Swiftnesses** [comment] 2019-04-30 15:03
Here's another:

```
# Example services.yaml entry

set_variable:
  # Description of the service
  description: Update a variables value and/or its attributes.
  # Different fields that your service accepts
  fields:
    # Key of the field
    variable:
      description: string (required) The name of the variable to update
    value:
      description: any (optional) New value to set
    value_template:
      description: template (optional) New value to set from a template
    attributes:
      description: dictionary (optional) Attributes to set or update
    attributes_template:
      description: template (optional) Attributes to set or update from a template ( should return a json object )
    replace_attributes:
      description: boolean ( optional ) Replace or merge current attributes (default false = merge)
```

**Comment by twrecked** [comment] 2019-04-30 15:04
Yes it does and it's actually a good thing. I've added some services and this will allow Home Assistant to show some help in the services tab. I'll look at it tonight.

**Comment by Swiftnesses** [comment] 2019-04-30 15:09
Cool, I've updated HA and pulled the latest branch and noticed my alarm panel went 'tits up' and now shows 'unknown', the service still works, thankfully. Known issue?

**Comment by twrecked** [comment] 2019-04-30 15:12
Do you run the native smartthings and have Arlo on that?

I ask because somebody else saw something similar and their alarm stopped working. Do the modes appear in the logs correctly? Something like:

```
 mode0 <==> disarmed
```

**Comment by Swiftnesses** [comment] 2019-04-30 15:13
No Smartthings, I'll need to check the logs later, it was working before, not sure when it stopped :/

**Comment by Swiftnesses** [comment] 2019-04-30 15:14
I have just noticed this:

```
2019-04-30 16:08:21 WARNING (MainThread) [homeassistant.helpers.service] Not passing an entity ID to a service to target all entities is deprecated. Update your call to alarm_control_panel.alarm_arm_away to be instead: entity_id: all
2019-04-30 16:08:33 WARNING (MainThread) [homeassistant.helpers.service] Not passing an entity ID to a service to target all entities is deprecated. Update your call to alarm_control_panel.alarm_disarm to be instead: entity_id: all
```

**Comment by twrecked** [comment] 2019-04-30 15:16
That's a change in Home Assistant. Can you try setting it to 'all'?

I've never really tried it. I do them individually.

**Comment by Swiftnesses** [comment] 2019-04-30 15:17
Sorry to sound dumb, what do I need to set to 'all'?

**Comment by Swiftnesses** [comment] 2019-04-30 15:19
Also found this:

```
2019-04-30 15:59:02 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 363, in _async_add_entity
    await entity.async_added_to_hass()
  File "/config/custom_components/aarlo/alarm_control_panel.py", line 107, in async_added_to_hass
    self._state = self._get_state_from_mode( self._base.attribute( 'activeMode' ) )
  File "/config/custom_components/aarlo/alarm_control_panel.py", line 160, in _get_state_from_mode
    lmode = mode.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by twrecked** [comment] 2019-04-30 15:19
I'm guessing the `entity_id`, something like this in the **Services** panel.

{
 "entity_id":"all"
}

**Comment by Swiftnesses** [comment] 2019-04-30 15:21
Hmmm, I'll try it, I get this when trying to set the mode via the alarm panel card, which doesn't work and just says state 'unknown', will check and revert.

**Comment by twrecked** [comment] 2019-04-30 15:23
I just tried here and it worked for me. But it sounds like you're not getting the modes from the base station. If you restart HA take a look for the modes being collected. It'll be near some logs containing the line `automation/definitions`.

**Comment by Swiftnesses** [comment] 2019-04-30 15:27
I restarted my Debian instance and it's working again, who knows!

**Comment by twrecked** [comment] 2019-04-30 15:30
Let me know if it happens again. Yesterday I had a back trace in the `web_socket` code so I'm thinking some strange things are afoot.

**Comment by maheus** [comment] 2019-05-02 17:59
hi, 

 i have a same problem , alarm panel show unknown and i have an error in log
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 363, in _async_add_entity
    await entity.async_added_to_hass()
  File "/home/homeassistant/.homeassistant/custom_components/aarlo/alarm_control_panel.py", line 107, in async_added_to_hass
    self._state = self._get_state_from_mode( self._base.attribute( 'activeMode' ) )
  File "/home/homeassistant/.homeassistant/custom_components/aarlo/alarm_control_panel.py", line 160, in _get_state_from_mode
    lmode = mode.lower()
```

but if i set a mode with service "alarm_control_panel.alarm_disarm" (by example) everything works.

**Comment by maheus** [comment] 2019-05-02 18:02
if i use v0.4 tag, everything works but i doesn't have the support of stream

**Comment by twrecked** [comment] 2019-05-02 18:15
I think I know what the issue is. I'll try and get a fix checked in later today.

It's probably never quite worked right at start up but by adding the call to `lower()` it's made the issue appear.

**Comment by maheus** [comment] 2019-05-02 18:21
ok i will  test without this call

**Comment by twrecked** [comment] 2019-05-02 18:25
You can try this branch:

  https://github.com/twrecked/hass-aarlo/tree/base-mode-fix

**Comment by maheus** [comment] 2019-05-02 18:43
correction is almost perfect ;), error is gone and control panel is returned. but the fisrt mode isn't good for me .
example my current mode was disarmed but after reboot the mode 'armed' who was displayed .
If i change the mode with application everything is ok
If i change the mode with homeassistant everything is ok

**Comment by twrecked** [comment] 2019-05-02 19:05
And I found the other bug! Give me a few mins...

**Comment by twrecked** [comment] 2019-05-02 20:03
@maheus 

The problem was I changed the way I collect the base mode information between 0.4 and (soon to be) 0.5. The old method would miss custom modes on some base stations. During the upgrade I forgot to add the code to read the initial mode from the base station.

Can you pull from the build and try again?

**Comment by maheus** [comment] 2019-05-02 20:11
perfect !

**Comment by twrecked** [comment] 2019-05-02 21:11
It's all merged back to master.

**Comment by twrecked** [comment] 2019-05-09 21:49
See previous comment.

**Closed by twrecked** 2019-05-09 21:49 UTC
