### ISSUE TITLE
Deprecated support features - quite a few of them

### ISSUE THREAD

**Issue by webwude** [twrecked/hass-aarlo#892] opened 2024-02-27 16:05 UTC
1. Logger: homeassistant.components.alarm_control_panel.const
Source: helpers/deprecation.py:205
Integration: Alarmanlage (documentation, issues)
First occurred: 08:02:04 (4 occurrences)
Last logged: 08:02:04

SUPPORT_ALARM_ARM_AWAY was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_AWAY instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues
SUPPORT_ALARM_ARM_HOME was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_HOME instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues
SUPPORT_ALARM_ARM_NIGHT was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_NIGHT instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues
SUPPORT_ALARM_TRIGGER was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.TRIGGER instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues

2. Logger: homeassistant.components.alarm_control_panel
Source: helpers/deprecation.py:205
Integration: Alarmanlage (documentation, issues)
First occurred: 08:02:04 (4 occurrences)
Last logged: 08:02:04

FORMAT_NUMBER was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.NUMBER instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues
FORMAT_TEXT was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.TEXT instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues

3. Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 08:01:50 (1 occurrences)
Last logged: 08:01:50

TEMP_CELSIUS was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues

**Comment by twrecked** [comment] 2024-03-03 21:39
Duplicate of 872.

**Closed by twrecked** 2024-03-03 21:39 UTC
