### ISSUE TITLE
Configuration not valid - CONF_ATTRIBUTION and DATA_ARLO issue

### ISSUE THREAD

**Issue by LaskaBozzolo** [twrecked/hass-aarlo#166] opened 2020-02-11 08:19 UTC
Hi, I updated to latest HACS. After that, I cannot get aarlo working any more. I always receive "configuration not valid" and these are the issues:

Platform error binary_sensor.aarlo - cannot import name 'CONF_ATTRIBUTION' from 'custom_components.aarlo' (/config/custom_components/aarlo/__init__.py)
Platform error switch.aarlo - cannot import name 'DATA_ARLO' from 'custom_components.aarlo' (/config/custom_components/aarlo/__init__.py)
Platform error sensor.aarlo - cannot import name 'CONF_ATTRIBUTION' from 'custom_components.aarlo' (/config/custom_components/aarlo/__init__.py)
Platform error alarm_control_panel.aarlo - cannot import name 'CONF_ATTRIBUTION' from 'custom_components.aarlo' (/config/custom_components/aarlo/__init__.py)

**Comment by devjj** [comment] 2020-02-11 08:32
I am having the same problem

**Comment by sebr** [comment] 2020-02-11 08:34
This looks to be a problem with latest HACS - see #165

**Comment by LaskaBozzolo** [comment] 2020-02-11 08:35
I'd like to add that I tried to downgrade HACS, but the problem still here

**Comment by LaskaBozzolo** [comment] 2020-02-11 08:37
> 
> 
> This looks to be a problem with latest HACS - see #165

I saw that, but I see that that issue is closed, and I didn't understand if there is any solution yet.

**Comment by sebr** [comment] 2020-02-11 08:41
Can you share the contents of your `custom_components/aarlo` directory?

**Comment by rafuz** [comment] 2020-02-11 08:53
I have done this:

1. Uninstall AArlo integration
2. Downgrade HACS to 20.9
3. Reboot Hass OS (Home Assistant does not restart with latest version of HACS)
4. Resintall AArlo integration
5. Restart Home Assistant (no reboot of OS needed now)

It works again.
Seems completely related to [https://github.com/twrecked/hass-aarlo/issues/165](#165 )

**Comment by LaskaBozzolo** [comment] 2020-02-11 08:58
> 
> 
> Did you reinstall `aarlo` after downgrading HACS? If so, can you please share the contents of your `custom_components/aarlo` directory?

Sorry, I didn't reinstall. I did that now, and it works again.
So I can confirm too, the procedure in #165 is right.

**Comment by rpitera** [comment] 2020-02-11 14:12
Would a manual install of the latest aarlo instead of downgrading HACS and installing it that way work as well?  I kind of don't want to downgrade HACS for an issue that only seems to be affecting one integration.  Of course, If I am missing something here please feel free to point it out.

**Comment by aneisch** [comment] 2020-02-11 14:26
> Would a manual install of the latest aarlo instead of downgrading HACS and installing it that way work as well? I kind of don't want to downgrade all of HACS for an issue that only seems to be affecting one integration. Of course, If I am missing something here please feel free to point it out.

Seems like if you installed via latest HACS and then fixed the directory structure afterward you'd be fine. There's a few other reports of directory structures not being correct with the latest HACS so I don't think it's only an issue with the aarlo integration.

**Comment by rpitera** [comment] 2020-02-11 14:46
Well, the only other verified issue I could see was with AppDaemon and I'm no longer using that.  I updated another integration and it installed fine, but then again that integration didn't have any subdirectories - which may be a factor.

Anyway, I just downloaded the zip of the latest master, deleted my existing custom_components/aarlo contents and uploaded the one from the zip.  Restarted and everything is working fine.  So that method seems to work as an alternative if others don't want to downgrade HACS.

**Comment by ludeeus** [comment] 2020-02-11 20:09
Fixed in https://github.com/hacs/integration/releases/tag/0.21.2

**Comment by townsmcp** [comment] 2020-02-12 14:20
@ludeeus nope, it isn’t. I just updated to 0.21.4 and get the same problems from above

**Comment by ludeeus** [comment] 2020-02-13 14:22
Then you:
A) did not reinstall hass-arlo after the upgrade.
B) did not restart Home Assistant after HACS upgrade and A

**Comment by guice** [comment] 2020-02-15 15:58
I can confirm reinstall arlo (then forcing an HA reboot) _after_ updating HACS works.

**Comment by sebr** [comment] 2020-02-16 22:05
@twrecked this can be closed

**Closed** 2020-02-19 19:47 UTC
