### ISSUE TITLE
Invalid config or authentication error

### ISSUE THREAD

**Issue by saman-github** [twrecked/hass-aarlo#864] opened 2024-01-18 10:21 UTC
Hi, I have been using Aarlo integration for long time and it was working perfect. from 16-01-2024 I get an error and Aarlo wont send 2fa mail to my gmail.
I tried to read all the issues and used all the advices but still it is not working.
here is the error and also my confige:

aarlo:
  host: https://my.arlo.com
  username: ***
  password: ***
  user_agent: random
  refresh_devices_every: 2
  stream_timeout: 120
  reconnect_every: 90
  tfa_host: 'imap.gmail.com'
  tfa_username: ***
  tfa_password: ***
  save_session: False
  backend: sse
  mode_api: auto

![image](https://github.com/twrecked/hass-aarlo/assets/76964430/6492eb80-cc3b-4d66-981c-b99091654fa0)
![image](https://github.com/twrecked/hass-aarlo/assets/76964430/f77a5cad-b4e1-45c6-a6a4-751b87cc69f1)

Logger: homeassistant.setup
Source: runner.py:188
First occurred: 11:11:55 (1 occurrences)
Last logged: 11:11:55

Setup of aarlo is taking over 10 seconds.

This error originated from a custom integration.

Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:716
Integration: aarlo (documentation, issues)
First occurred: 11:11:48 (4 occurrences)
Last logged: 11:13:44

authentication failed

This error originated from a custom integration.

Logger: custom_components.aarlo
Source: custom_components/aarlo/__init__.py:495
Integration: aarlo (documentation, issues)
First occurred: 11:11:48 (4 occurrences)
Last logged: 11:13:44

unable to connect to Arlo: attempt=1,sleep=15,error=authentication failed
unable to connect to Arlo: attempt=2,sleep=30,error=authentication failed
unable to connect to Arlo: attempt=3,sleep=60,error=authentication failed
unable to connect to Arlo: attempt=4,sleep=120,error=authentication failed

Logger: homeassistant.setup
Source: setup.py:221
First occurred: 11:13:44 (1 occurrences)
Last logged: 11:13:44

Setup failed for custom integration 'aarlo': Integration failed to initialize.

**Comment by petepall** [comment] 2024-01-23 22:02
@saman-github , I have the same issue since noon today.
Did you find any solution on this?

**Comment by saman-github** [comment] 2024-01-24 12:59
@petepall unfortunately not. It is very unstable, means it works oneday and then it gives error the other day.
It seems developers are too busy :(

**Comment by twrecked** [comment] 2024-01-24 13:23
@saman-github You're seeing cloud flare issues, check the other issues raised for cloud flare for solutions

@petepall Looks like a password mismatch. Does it have any special characters that could be interpreted during the YAML parsing? Does it need to be quoted?

Another thing to try would be to turn [verbose debug](https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#verbose-debug) and it will show you what password the code is trying to send.

**Comment by petepall** [comment] 2024-01-24 20:02
@twrecked, I switched on the verbose setting and I see in the logs that it's sending the wrong credentials.
These are not what is in the aarlo.yaml config.
Where is it pulling this information from?

2024-01-24 20:53:44.519 DEBUG (SyncWorker_10) [custom_components.aarlo.cfg] options={'tfa_source': 'imap', 'tfa_type': 'email', 'tfa_host': 'imap.gmail.com', 'tfa_username': 'xxxxx@gmail.com', 'tfa_password': 'xxxxx', 'username': 'xxxx@gmail.com', 'password': 'xxxxx'

**Comment by twrecked** [comment] 2024-01-24 20:10
@petepall Which version are you using?

**Comment by petepall** [comment] 2024-01-24 20:18
version 0.8.1 (alpha 10).

Seems that the issue is that it's not reading the secrets.yaml file.
I just added the password and the app password directly into the aarlo.yaml file and now it reads the correct credentials.

However this is not really ok as we should not have credentials directly into the config file.

**Comment by twrecked** [comment] 2024-01-24 20:23
Did you upgrade from 0.7 or install 0.8 directly?

**Comment by petepall** [comment] 2024-01-24 20:25
I upgraded from 0.7

I just confirmed that if I put the credentials back in the secrets file it's not working.
When the credentials are in the secrets it' s reverting back to the obsolete login credentials, so those must be stored somewhere in the system

**Comment by petepall** [comment] 2024-01-24 20:25
[custom_components.aarlo] async setup for aarlo
2024-01-24 21:22:35.694 DEBUG (MainThread) [custom_components.aarlo.cfg] failed to read aarlo config Secrets not supported in this YAML file
2024-01-24 21:22:35.696 DEBUG (MainThread) [custom_components.aarlo.cfg] l-config-file=/config/aarlo.yaml

**Comment by twrecked** [comment] 2024-01-24 20:29
When i_Aarlo_ moved to config-flow (when you upgraded) it moved all your passwords into the standard config location. You don't need to add your username or 2fa information into the `aarlo.yaml` file. You should delete them from your `aarlo.yaml` file.

Look for `aarlo` in `.storage/core.config_entries` and check the password in there. If it looks wrong then change it.

I've just noticed there is no way what to change the password for the integration but that seems to be lacking from all the integrations. I'll look into that anyway.

**Comment by petepall** [comment] 2024-01-24 20:46
Thanks, Updated the enty in the `.storage/core.config_entries` did the trick.

**Comment by saman-github** [comment] 2024-01-26 12:52
@petepall: can you help me about how did you update the aarlo from 0.7 to 0.8? Hacs doesn't update it and I could not find anything in documentation regarding updates.

**Comment by saman-github** [comment] 2024-01-26 12:54
> @saman-github You're seeing cloud flare issues, check the other issues raised for cloud flare for solutions
> 
> @petepall Looks like a password mismatch. Does it have any special characters that could be interpreted during the YAML parsing? Does it need to be quoted?
> 
> Another thing to try would be to turn [verbose debug](https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#verbose-debug) and it will show you what password the code is trying to send.

Thanks for answer, I checked all the posts regarding cloudflare and did everything, but still it is not stable. so sometime I get the error and then after some restarts, it works again with no issue.

**Comment by petepall** [comment] 2024-01-27 20:06
Hi @saman-github, I had an issue with the password not being ok. based on the info from twrecked I was able to change the password which is in the file mentioned in one of the email.

I did not have an issue with Cloudflare.

**Comment by saman-github** [comment] 2024-01-28 18:31
> I upgraded from 0.7
> 
> I just confirmed that if I put the credentials back in the secrets file it's not working. When the credentials are in the secrets it' s reverting back to the obsolete login credentials, so those must be stored somewhere in the system

@petepall : Can you help me to find how to upgrade from 0.7 to 0.8? I can not find it in documentation.

**Comment by saman-github** [comment] 2024-01-28 18:39
> @saman-github You're seeing cloud flare issues, check the other issues raised for cloud flare for solutions
> 
> @petepall Looks like a password mismatch. Does it have any special characters that could be interpreted during the YAML parsing? Does it need to be quoted?
> 
> Another thing to try would be to turn [verbose debug](https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#verbose-debug) and it will show you what password the code is trying to send.

@twrecked : I did all advices I found in the issues section and still I have no success. Can you please help me more?
Hacs doesn't show me to upgrade to 0.8 and it shows v0.7.4.2 as the latest version.
I addedd:
  mqtt_hostname_check: False
  mqtt_host: mqtt-cluster-z1.arloxcld.com
to configuration and nothing happened. buying Arlo was one of my biggest mistakes :D :(

**Comment by twrecked** [comment] 2024-01-29 14:28
@saman-github We'll get you going again, _Arlo_ is always playing around with their setup.

First thing, try removing the `host` line from your config.

**Comment by saman-github** [comment] 2024-01-30 08:22
> @saman-github We'll get you going again, _Arlo_ is always playing around with their setup.
> 
> First thing, try removing the `host` line from your config.

Hi again @twrecked : as I told you it is very unstable for me.
Now it started to work from yesterday morning.
I changed my configurator to this and it is working for now:

aarlo:
  username: ***
  password: ***
  tfa_source: imap
  tfa_type: email
  tfa_host: 'imap.gmail.com'
  tfa_username: ***
  tfa_password: ***
  refresh_devices_every: 2
  stream_timeout: 120
  reconnect_every: 60
  backend: sse
  mqtt_hostname_check: False
  mqtt_host: mqtt-cluster-z1.arloxcld.com
  user_agent: random
  save_session: False
  mode_api: auto

**Comment by saman-github** [comment] 2024-02-01 17:59
> > @saman-github We'll get you going again, _Arlo_ is always playing around with their setup.
> > First thing, try removing the `host` line from your config.
> 
> Hi again @twrecked : as I told you it is very unstable for me. Now it started to work from yesterday morning. I changed my configurator to this and it is working for now:
> 
> aarlo: username: *** password: *** tfa_source: imap tfa_type: email tfa_host: 'imap.gmail.com' tfa_username: *** tfa_password: *** refresh_devices_every: 2 stream_timeout: 120 reconnect_every: 60 backend: sse mqtt_hostname_check: False mqtt_host: mqtt-cluster-z1.arloxcld.com user_agent: random save_session: False mode_api: auto

Again today it is not working . . .

**Comment by twrecked** [comment] 2024-02-01 18:02
Did you put the host back into the config?

Try removing the `user_agent` random and the `save_session` settings.

If that doesn't work send me some encrypted logs.

**Comment by saman-github** [comment] 2024-02-12 12:09
> Did you put the host back into the config?
> 
> Try removing the `user_agent` random and the `save_session` settings.
> 
> If that doesn't work send me some encrypted logs.

Hi, For now it is working. sometimes it gives the errore and  Irestart the HA one or 2 times and it works again. I dont know what is the magic but I hope it continiue working :)
The configuration is as below:

aarlo:
  username: ***
  password: ***
  tfa_source: imap
  tfa_type: email
  tfa_host: 'imap.gmail.com'
  tfa_username: ***
  tfa_password: ***
  refresh_devices_every: 2
  stream_timeout: 120
  reconnect_every: 60
  backend: sse
  mqtt_hostname_check: False
  mqtt_host: mqtt-cluster-z1.arloxcld.com
  user_agent: random
  save_session: False
  mode_api: auto

**Comment by twrecked** [comment] 2024-05-23 17:16
I'll close this for now, but open a new issue if it breaks again.

**Closed by twrecked** 2024-05-23 17:16 UTC

**Comment by sirajkas** [comment] 2025-04-13 23:19
having the same issue.. .
unable to connect to Arlo: attempt=1,sleep=15,error=login failed: 401 - Password not correct
unable to connect to Arlo: attempt=2,sleep=30,error=login failed: 401 - Password not correct
unable to connect to Arlo: attempt=3,sleep=60,error=login failed: 401 - Password not correct
unable to connect to Arlo: attempt=3,sleep=60,error=login failed: 403 - Account locked
