### ISSUE TITLE
FORMAT_NUMBER error

### ISSUE THREAD

**Issue by PrimitixLuke** [twrecked/hass-aarlo#882] opened 2024-02-07 21:22 UTC
Logger: homeassistant.components.alarm_control_panel
Source: helpers/deprecation.py:205
Integration: Pannello di controllo degli allarmi (documentation, issues)
First occurred: 22:15:28 (4 occurrences)
Last logged: 22:15:28

FORMAT_NUMBER was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.NUMBER instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues
FORMAT_TEXT was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.TEXT instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues

**Comment by twrecked** [comment] 2024-02-07 21:34
Duplicate of #872

**Closed by twrecked** 2024-02-07 21:34 UTC
