### ISSUE TITLE
Becomes unresponsive after a few days

### ISSUE THREAD

**Issue by jaburgeson** [twrecked/hass-aarlo#147] opened 2020-01-08 15:47 UTC
First of all, thanks for building this plugin!  

I've been using this plugin over the past few months testing, updating, and trying to use to build automations with.

However, after an uncertain amount of time...could be 2 hours, could be 2 days, all of my Arlo devices become unresponsive.

I am unable to take snapshots, sound the siren, or set modes.  Also status updates aren't being pushed into Home Assistant.

Last week and took an unused Raspberry Pi, install Hassio and only Aarlo on it to make sure it isn't something else causing issue, and it has become unresponsive twice.

A restart of Home Assistant services fixes the issue.  I'm not sure if this is because Aarlo is re-logging back in to the Arlo servers to force an update.

I am running 0.6.6 and now 0.6.7 with version 0.103.5 of Hassio.

**Comment by twrecked** [comment] 2020-01-08 16:13
Would you be ok to look through the debug? This is a problem I encounter some times and is to do with the Arlo web interface not really being designed for long term connections.

I'm trying to come up with ways to work around the issue.

**Comment by jaburgeson** [comment] 2020-01-08 22:19
Is there anything I need to do beyond just looking at the Log in the Developer Tools section?

Everything is working fine right now, but there are quite a few messages related to pyarlo.

homeassistant.exceptions.HomeAssistantError: Entity id already exists: binary_sensor.aarlo_motion_front_door. Platform aarlo does not generate unique IDs
2020-01-08 10:53:05 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-08 10:53:17 WARNING (MainThread) [homeassistant.setup] Setup of default_config is taking over 10 seconds.
2020-01-08 10:53:21 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-08 10:53:21 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-08 10:53:22 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-08 10:54:06 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-08 11:03:15 WARNING (ArloEventStream) [pyaarlo] general exception can only concatenate str (not "NoneType") to str
2020-01-08 11:13:15 WARNING (ArloEventStream) [pyaarlo] general exception can only concatenate str (not "NoneType") to str
2020-01-08 11:23:43 WARNING (ArloEventStream) [pyaarlo] general exception can only concatenate str (not "NoneType") to str
2020-01-08 11:33:15 WARNING (ArloEventStream) [pyaarlo] general exception can only concatenate str (not "NoneType") to str
2020-01-08 11:43:15 WARNING (ArloEventStream) [pyaarlo] general exception can only concatenate str (not "NoneType") to str
2020-01-08 11:53:15 WARNING (ArloEventStream) [pyaarlo] general exception can only concatenate str (not "NoneType") to str
2020-01-08 12:13:17 WARNING (ArloEventStream) [pyaarlo] general exception can only concatenate str (not "NoneType") to str

**Comment by jaburgeson** [comment] 2020-01-09 19:21
So, I just did some testing.  It appears if the internet goes down for a short period of time, the plugin fails to reconnect back to Arlo servers and it remains in limbo.  I can verify this by shutting the port down on the switch that the raspberry pi is connect to for a few minutes and then bringing it back up.  Home Assistant works fine, but the plugin is now no longer connected.

Maybe there is a way to verify connection every minute or so, and if not reconnected, initiate a relogin?

Here are the logs

2020-01-09 13:23:16 WARNING (ArloEventStream) [pyaarlo] general exception can only concatenate str (not "NoneType") to str
2020-01-09 13:27:45 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 788, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
2020-01-09 13:27:45 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 815, in _resolve_host
    await event.wait()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/locks.py", line 37, in wait
    raise self._exc
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 788, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
2020-01-09 13:27:50 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 788, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
2020-01-09 13:27:57 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 788, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
2020-01-09 13:28:02 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 788, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
2020-01-09 13:28:04 WARNING (ArloBackgroundWorker) [pyaarlo] request-error=ReadTimeout
2020-01-09 13:28:09 WARNING (ArloBackgroundWorker) [pyaarlo] request-error=ConnectionError
2020-01-09 13:28:13 ERROR (MainThread) [backoff] Giving up get_ratelimit(...) after 5 tries (concurrent.futures._base.TimeoutError)
2020-01-09 13:28:13 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 788, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
2020-01-09 13:28:13 ERROR (MainThread) [backoff] Giving up get_ratelimit(...) after 5 tries (aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.github.com:443 ssl:None [Try again])
2020-01-09 13:28:14 WARNING (ArloBackgroundWorker) [pyaarlo] request-error=ConnectionError
2020-01-09 13:28:18 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 788, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
2020-01-09 13:28:19 WARNING (ArloBackgroundWorker) [pyaarlo] request-error=ConnectionError
2020-01-09 13:28:24 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 788, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
2020-01-09 13:28:24 WARNING (ArloBackgroundWorker) [pyaarlo] request-error=ConnectionError
2020-01-09 13:28:29 WARNING (ArloBackgroundWorker) [pyaarlo] request-error=ConnectionError
2020-01-09 13:28:29 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 788, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
2020-01-09 13:28:34 WARNING (ArloBackgroundWorker) [pyaarlo] request-error=ConnectionError
2020-01-09 13:28:35 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 788, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
2020-01-09 13:28:39 WARNING (ArloBackgroundWorker) [pyaarlo] request-error=ConnectionError
2020-01-09 13:28:44 WARNING (ArloBackgroundWorker) [pyaarlo] request-error=ConnectionError
2020-01-09 13:28:44 ERROR (MainThread) [backoff] Giving up get_ratelimit(...) after 5 tries (concurrent.futures._base.TimeoutError)
2020-01-09 13:28:44 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 788, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
2020-01-09 13:28:44 ERROR (MainThread) [backoff] Giving up get_ratelimit(...) after 5 tries (aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.github.com:443 ssl:None [Try again])
2020-01-09 13:28:49 WARNING (ArloBackgroundWorker) [pyaarlo] request-error=ConnectionError
2020-01-09 13:28:49 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 788, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
2020-01-09 13:28:54 WARNING (ArloBackgroundWorker) [pyaarlo] request-error=ConnectionError
2020-01-09 13:28:54 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 788, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
2020-01-09 13:28:59 WARNING (ArloBackgroundWorker) [pyaarlo] request-error=ConnectionError
2020-01-09 13:29:00 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 788, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
2020-01-09 13:29:04 WARNING (ArloBackgroundWorker) [pyaarlo] request-error=ConnectionError
2020-01-09 13:29:06 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 788, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
2020-01-09 13:29:09 WARNING (ArloBackgroundWorker) [pyaarlo] request-error=ConnectionError
2020-01-09 13:29:14 WARNING (ArloBackgroundWorker) [pyaarlo] request-error=ConnectionError
2020-01-09 13:29:15 ERROR (MainThread) [backoff] Giving up get_ratelimit(...) after 5 tries (concurrent.futures._base.TimeoutError)
2020-01-09 13:29:15 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 788, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
2020-01-09 13:29:15 ERROR (MainThread) [backoff] Giving up get_ratelimit(...) after 5 tries (aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.github.com:443 ssl:None [Try again])
2020-01-09 13:29:19 WARNING (ArloBackgroundWorker) [pyaarlo] request-error=ConnectionError
2020-01-09 13:29:23 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 788, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
2020-01-09 13:29:24 WARNING (ArloBackgroundWorker) [pyaarlo] request-error=ConnectionError
2020-01-09 13:29:28 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 788, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
2020-01-09 13:29:29 WARNING (ArloBackgroundWorker) [pyaarlo] request-error=ConnectionError
2020-01-09 13:29:32 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-09 13:29:32 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-09 13:29:32 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-09 13:29:33 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-09 13:29:33 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-09 13:29:34 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-09 13:30:33 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-09 13:30:33 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-09 13:30:34 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-09 13:30:34 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-09 13:31:04 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-09 13:31:04 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-09 13:31:05 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-09 13:31:05 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-09 14:12:02 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-09 14:12:03 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-09 14:12:04 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-09 14:12:05 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-09 14:12:06 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-09 14:12:07 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-01-09 14:13:04 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}

**Comment by twrecked** [comment] 2020-01-09 19:42
That seems like a simple test, I'll take a look tonight. The code should do it's best to reconnect but I guess the mechanism is broken.

I just put a change in to not close the socket - the close() call was hanging - but I bet that is the issue.

**Comment by twrecked** [comment] 2020-01-09 21:47
Can you try adding these to you config:

```yaml
aarlo:
  refresh_devices_every: 1
  stream_timeout: 75
```

It should attempt a reconnect when it detects the stream has gone away.

**Comment by jaburgeson** [comment] 2020-01-10 02:02
I just ran the test again with the config change you mentioned and it appears to have come back after losing network access for 10 minutes.  I’ll continue to monitor and report back over the next few days!

Thanks for your help on this issue and making this plugin!

**Comment by twrecked** [comment] 2020-01-10 02:46
I'm starting to think I need to improve the docs - or at least give a decent starting configuration!

Let me know how it goes, it might still lock up because as I mentioned I really don't think the web interface was designed to be used this way, but I can keep adding work arounds in.

**Comment by twrecked** [comment] 2020-03-24 12:48
Closing because I'm assuming it's working.

**Closed by twrecked** 2020-03-24 12:48 UTC
